apiVersion: v1
kind: Service
metadata:
  name: postgresql-ha-pgadmin
  namespace: dev-postgresql
  labels:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/name: postgresql-ha
spec:
  selector:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/name: postgresql-ha
  ports:
    - name: pgadmin
      protocol: TCP
      port: 80
      targetPort: pgadmin
