metrics:
  containerSecurityContext:
    enabled: false
  securityContext:
    enabled: false
persistence:
  size: 100Gi
pgpool:
  containerSecurityContext:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  securityContext:
    enabled: false
  sidecars:
  - name: pgadmin
    image: docker.io/dpage/pgadmin4
    imagePullPolicy: Always
    ports:
    - name: pgadmin
      containerPort: 80
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: "username@example.com"
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "password"
postgresql:
  containerSecurityContext:
    enabled: false
  securityContext:
    enabled: false
volumePermissions:
  enable: true